# Generated by Django 4.0.1 on 2022-04-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeladministrateur',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
