# Generated by Django 4.0.1 on 2022-04-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0003_modeladministrateur_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='modelEtablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
                ('telephone', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('ville', models.CharField(max_length=200, null=True)),
                ('pays', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
