# Generated by Django 4.0.1 on 2022-04-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0004_modeletablissement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modeladministrateur',
            old_name='etablissement',
            new_name='confirmPassword',
        ),
        migrations.RemoveField(
            model_name='modeladministrateur',
            name='username',
        ),
        migrations.AddField(
            model_name='modeladministrateur',
            name='prenom',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
