# Generated by Django 4.0.1 on 2022-04-16 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0005_rename_etablissement_modeladministrateur_confirmpassword_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modeletablissement',
            old_name='created_at',
            new_name='created_etablissement_at',
        ),
        migrations.RenameField(
            model_name='modeletablissement',
            old_name='nom',
            new_name='nomEtablissement',
        ),
    ]
