# Generated by Django 4.0.1 on 2022-04-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0006_rename_created_at_modeletablissement_created_etablissement_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeladministrateur',
            name='nomDUtilisateur',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
