# Generated by Django 4.0.1 on 2022-04-21 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0007_modeladministrateur_nomdutilisateur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modeladministrateur',
            old_name='nomDUtilisateur',
            new_name='username',
        ),
    ]
