# Generated by Django 4.0.1 on 2022-04-23 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0008_rename_nomdutilisateur_modeladministrateur_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='modelAdministrateur',
        ),
    ]
