# Generated by Django 4.0.1 on 2022-05-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0010_alter_modeletablissement_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeletablissement',
            name='telephone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
