# Generated by Django 4.0.1 on 2022-05-18 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrateur', '0011_alter_modeletablissement_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeletablissement',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
